[workspace]
resolver = "2"
members = [
    "crates/bevscode",
    "crates/bevy_lsp",
    "crates/bevsterm",
    "crates/bevy_instanced_text",
    "crates/bevy_instanced_text_edit",
    "crates/bevy_text_interaction",
    "crates/bevy_text_editor",
    "crates/bevy_tree_sitter",
    "examples",
]

[profile.release]
debug = true
